guards:
  - name: "detect_jailbreak"
    type: "detect_jailbreak"
    enabled: true
    on_fail: "filter"

  - name: "output_validation"
    type: "output_validation"
    enabled: true
    on_fail: "reask"

input_validation:
  max_length: 2000
  min_length: 1

output_validation:
  max_length: 4000
  check_relevance: true
