version: '3.8'

services:
  chatbot:
    build: .
    container_name: llm-chatbot
    environment:
      - LLM_PROVIDER=openai
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE_URL=${LLM_API_BASE_URL:-}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-gpt-4o-mini}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-1000}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - TOP_K_RESULTS=${TOP_K_RESULTS:-3}
    volumes:
      - ./data/documents:/app/data/documents:ro
      - ./data/vectordb:/app/data/vectordb
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    command: python main.py
    
  # Service for initializing knowledge base
  chatbot-init:
    build: .
    container_name: llm-chatbot-init
    environment:
      - LLM_PROVIDER=openai
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE_URL=${LLM_API_BASE_URL:-}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
    volumes:
      - ./data/documents:/app/data/documents:ro
      - ./data/vectordb:/app/data/vectordb
    command: python main.py --init-kb
    profiles:
      - init